version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example_db
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

  php:
    build: .
    restart: always
    volumes:
      - "D:/jaime/retohambuerguesa/backend:/var/www/html/backend"
      - "D:/jaime/retohambuerguesa/backend/imagenes:/var/www/html/public/imagenes"  # 🔥 Se agregó la carpeta de imágenes
    ports:
      - "8000:80"
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data

volumes:
  mysql:
